#!/bin/bash
# deploy/local/compose/rails/start

set -o errexit
set -o pipefail
set -o nounset

# Create and migrate database if needed
rails db:prepare

# Run the development server
exec rails server -b 0.0.0.0 -p 8000
