#!/bin/bash
# deploy/local/compose/rails/sidekiq/worker/start

set -o errexit
set -o pipefail
set -o nounset

# Wait for postgres and redis to be ready
bundle exec rails db:prepare

# Run Sidekiq worker
exec bundle exec sidekiq
