# .github/dependabot.yml
version: 2
updates:
  # Update Ruby gems
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "ruby"
    commit-message:
      prefix: "chore"
      include: "scope"

  # Update GitHub Actions
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "ci"
      include: "scope"

  # Update Docker base images
  - package-ecosystem: docker
    directory: "/deploy/local/compose/rails"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"

  - package-ecosystem: docker
    directory: "/deploy/production/compose/rails"
    schedule:
      interval: weekly
    open-pull-requests-limit: 5
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "docker"
      include: "scope"
