#!/bin/bash
# deploy/production/compose/rails/migrate

set -o errexit
set -o pipefail
set -o nounset

# Only create/migrate DB if it doesn't exist or has pending migrations
if ! ./bin/rails db:version &>/dev/null; then
  echo "Database not found, creating..."
  ./bin/rails db:create db:schema:load
else
  echo "Running migrations..."
  ./bin/rails db:migrate
fi
