#!/bin/bash
# deploy/production/compose/rails/start

set -o errexit
set -o pipefail
set -o nounset

# Run database migrations
rails db:migrate

# Start the Rails server with Thruster
exec ./bin/thrust ./bin/rails server -b 0.0.0.0 -p 8000